import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * One sidebar. Hand-written guides first, then the generated references
 * (API from the OpenAPI document, CLI from the command tree) and the
 * repository documents synced at build time, in their curated order.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: ['getting-started/run-locally', 'getting-started/startup-check'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['guides/app', 'guides/cli', 'guides/api', 'guides/performance', 'guides/security'],
    },
    {
      type: 'category',
      label: 'API reference',
      link: { type: 'doc', id: 'api/index' },
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    {
      type: 'category',
      label: 'CLI reference',
      link: { type: 'doc', id: 'cli/index' },
      items: [{ type: 'autogenerated', dirName: 'cli' }],
    },
    {
      type: 'category',
      label: 'Backend contract',
      items: [{ type: 'autogenerated', dirName: 'reference/markov' }],
    },
    {
      type: 'category',
      label: 'App (markov.pet)',
      items: [{ type: 'autogenerated', dirName: 'reference/frontend' }],
    },
    {
      type: 'category',
      label: 'Session evidence',
      items: [{ type: 'autogenerated', dirName: 'reference/sessions' }],
    },
    'contributing',
  ],
};

export default sidebars;
