import {
  corporateActionListResponseSchema,
  effectiveLimitsResponseSchema,
  errorResponseSchema,
  instrumentDetailSchema,
  instrumentListResponseSchema,
  mappingResponseSchema,
  meResponseSchema,
  platformInfoResponseSchema,
  publicThesisSchema,
  researchRunSchema,
  revisionListResponseSchema,
  runListResponseSchema,
  sessionResponseSchema,
  sourceListResponseSchema,
  sourceRecordSchema,
  strategyDetailSchema,
  strategyDraftSchema,
  strategyLimitsSchema,
  strategyListResponseSchema,
  strategySchema,
  thesisDetailSchema,
  thesisListResponseSchema,
  thesisRevisionSchema,
  watchlistSchema,
} from '@markov/contracts';
import type { ZodType } from 'zod';

export interface ContractMatrixEntry {
  /** Screen or server capability that depends on the operation. */
  readonly consumer: string;
  readonly method: 'get' | 'post' | 'delete' | 'put' | 'patch';
  readonly path: string;
  /** Success status the consumer relies on. */
  readonly status: number;
  /** Runtime schema the consumer validates the success body with; null for empty bodies. */
  readonly responseSchema: ZodType | null;
  /** Error codes the consumer handles distinctly; everything else is a generic failure. */
  readonly handledErrors: readonly string[];
}

/**
 * Route-to-contract matrix for the app. `test/compatibility.test.ts` proves
 * every entry exists in the frozen OpenAPI document with the same response
 * shape, so a renamed field or removed route fails the frontend build, not
 * the user.
 */
export const CONTRACT_MATRIX: readonly ContractMatrixEntry[] = [
  {
    consumer: 'Top bar connection status; sign-in provider availability',
    method: 'get',
    path: '/v1/platform',
    status: 200,
    responseSchema: platformInfoResponseSchema,
    handledErrors: [],
  },
  {
    consumer: 'Sign-in (server exchange of the identity token)',
    method: 'post',
    path: '/v1/auth/sessions',
    status: 201,
    responseSchema: sessionResponseSchema,
    handledErrors: ['AUTH_REQUIRED', 'RATE_LIMITED', 'VALIDATION_FAILED'],
  },
  {
    consumer: 'Session resolution on every request; account controls',
    method: 'get',
    path: '/v1/me',
    status: 200,
    responseSchema: meResponseSchema,
    handledErrors: ['AUTH_REQUIRED'],
  },
  {
    consumer: 'Sign out',
    method: 'delete',
    path: '/v1/auth/sessions/current',
    status: 204,
    responseSchema: null,
    handledErrors: ['AUTH_REQUIRED'],
  },
  {
    consumer: 'Explore: instruments tab (search, filters, bounded pagination)',
    method: 'get',
    path: '/v1/catalog/instruments',
    status: 200,
    responseSchema: instrumentListResponseSchema,
    handledErrors: ['VALIDATION_FAILED', 'RATE_LIMITED', 'PROVIDER_UNAVAILABLE'],
  },
  {
    consumer: 'Market detail: identity, price, verification, lifecycle, availability',
    method: 'get',
    path: '/v1/catalog/instruments/{instrumentId}',
    status: 200,
    responseSchema: instrumentDetailSchema,
    handledErrors: ['NOT_FOUND'],
  },
  {
    consumer: 'Market detail: lifecycle notices',
    method: 'get',
    path: '/v1/catalog/instruments/{instrumentId}/corporate-actions',
    status: 200,
    responseSchema: corporateActionListResponseSchema,
    handledErrors: ['NOT_FOUND'],
  },
  {
    consumer: 'Explore: watchlist tab and saved toggles',
    method: 'get',
    path: '/v1/me/watchlist',
    status: 200,
    responseSchema: watchlistSchema,
    handledErrors: ['AUTH_REQUIRED'],
  },
  {
    consumer: 'Save an instrument',
    method: 'put',
    path: '/v1/me/watchlist/items/{instrumentId}',
    status: 200,
    responseSchema: watchlistSchema,
    handledErrors: ['ASSET_NOT_ADMITTED', 'IDEMPOTENCY_CONFLICT', 'NOT_FOUND', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Remove a saved instrument',
    method: 'delete',
    path: '/v1/me/watchlist/items/{instrumentId}',
    status: 200,
    responseSchema: watchlistSchema,
    handledErrors: ['IDEMPOTENCY_CONFLICT', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Research workspace: own theses; market detail: theses mentioning an instrument',
    method: 'get',
    path: '/v1/me/theses',
    status: 200,
    responseSchema: thesisListResponseSchema,
    handledErrors: ['AUTH_REQUIRED'],
  },
  {
    consumer: 'Start a thesis (first revision)',
    method: 'post',
    path: '/v1/me/theses',
    status: 201,
    responseSchema: thesisDetailSchema,
    handledErrors: ['VALIDATION_FAILED', 'AUTH_REQUIRED', 'RATE_LIMITED'],
  },
  {
    consumer: 'Thesis editor: thesis, current revision and sources',
    method: 'get',
    path: '/v1/me/theses/{thesisId}',
    status: 200,
    responseSchema: thesisDetailSchema,
    handledErrors: ['NOT_FOUND', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Publish, make private again or archive a thesis',
    method: 'patch',
    path: '/v1/me/theses/{thesisId}',
    status: 200,
    responseSchema: thesisDetailSchema,
    handledErrors: ['NOT_FOUND', 'FORBIDDEN', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Save the thesis (append an immutable revision)',
    method: 'post',
    path: '/v1/me/theses/{thesisId}/revisions',
    status: 201,
    responseSchema: thesisRevisionSchema,
    handledErrors: ['VALIDATION_FAILED', 'NOT_FOUND', 'AUTH_REQUIRED', 'RATE_LIMITED'],
  },
  {
    consumer: 'Saved revisions list',
    method: 'get',
    path: '/v1/me/theses/{thesisId}/revisions',
    status: 200,
    responseSchema: revisionListResponseSchema,
    handledErrors: ['NOT_FOUND', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Sources panel: attach a URL (retrieved by the API under its safe-retrieval policy)',
    method: 'post',
    path: '/v1/me/theses/{thesisId}/sources',
    status: 201,
    responseSchema: sourceRecordSchema,
    handledErrors: ['VALIDATION_FAILED', 'NOT_FOUND', 'AUTH_REQUIRED', 'RATE_LIMITED'],
  },
  {
    consumer: 'Sources panel: source records with their status and dates',
    method: 'get',
    path: '/v1/me/theses/{thesisId}/sources',
    status: 200,
    responseSchema: sourceListResponseSchema,
    handledErrors: ['NOT_FOUND', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Shortlist: company names to admitted instruments (deterministic mapping)',
    method: 'post',
    path: '/v1/me/research/mappings',
    status: 200,
    responseSchema: mappingResponseSchema,
    handledErrors: ['VALIDATION_FAILED', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Bounded research run over chosen sources',
    method: 'post',
    path: '/v1/me/research/runs',
    status: 201,
    responseSchema: researchRunSchema,
    handledErrors: [
      'PROVIDER_UNAVAILABLE',
      'VALIDATION_FAILED',
      'NOT_FOUND',
      'AUTH_REQUIRED',
      'RATE_LIMITED',
    ],
  },
  {
    consumer: 'Research runs of a thesis',
    method: 'get',
    path: '/v1/me/research/runs',
    status: 200,
    responseSchema: runListResponseSchema,
    handledErrors: ['AUTH_REQUIRED'],
  },
  {
    consumer: 'Run progress (polled while queued or running)',
    method: 'get',
    path: '/v1/me/research/runs/{runId}',
    status: 200,
    responseSchema: researchRunSchema,
    handledErrors: ['NOT_FOUND', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Cancel a run',
    method: 'post',
    path: '/v1/me/research/runs/{runId}/cancel',
    status: 200,
    responseSchema: researchRunSchema,
    handledErrors: ['NOT_FOUND', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Public thesis page (published projection, no private notes, no owner)',
    method: 'get',
    path: '/v1/research/theses/{thesisId}',
    status: 200,
    responseSchema: publicThesisSchema,
    handledErrors: ['NOT_FOUND'],
  },
  {
    consumer: 'Shortlist to basket: recipe rules of this deployment',
    method: 'get',
    path: '/v1/strategies/limits',
    status: 200,
    responseSchema: strategyLimitsSchema,
    handledErrors: [],
  },
  {
    consumer: 'Shortlist to basket: create a basket draft from admitted instruments',
    method: 'post',
    path: '/v1/me/strategies',
    status: 201,
    responseSchema: strategyDetailSchema,
    handledErrors: ['VALIDATION_FAILED', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Build page: the person’s basket drafts',
    method: 'get',
    path: '/v1/me/strategies',
    status: 200,
    responseSchema: strategyListResponseSchema,
    handledErrors: ['AUTH_REQUIRED'],
  },
  {
    consumer: 'Basket builder: one draft identity with its validated draft and versions',
    method: 'get',
    path: '/v1/me/strategies/{strategyId}',
    status: 200,
    responseSchema: strategyDetailSchema,
    handledErrors: ['NOT_FOUND', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Basket builder: revision-checked autosave of the draft',
    method: 'put',
    path: '/v1/me/strategies/{strategyId}/draft',
    status: 200,
    responseSchema: strategyDraftSchema,
    handledErrors: ['IDEMPOTENCY_CONFLICT', 'VALIDATION_FAILED', 'NOT_FOUND', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Basket builder: archive or restore a draft',
    method: 'patch',
    path: '/v1/me/strategies/{strategyId}',
    status: 200,
    responseSchema: strategySchema,
    handledErrors: ['NOT_FOUND', 'AUTH_REQUIRED'],
  },
  {
    consumer: 'Set Rules: the limits that apply to the person now',
    method: 'get',
    path: '/v1/me/limits',
    status: 200,
    responseSchema: effectiveLimitsResponseSchema,
    handledErrors: ['AUTH_REQUIRED'],
  },
];

export const ERROR_ENVELOPE_SCHEMA = errorResponseSchema;
